-- Supabase schema (as provided) for storing client users.
-- Run this in Supabase SQL editor.

create table if not exists public.clients (
  id bigint generated by default as identity not null,
  username character varying not null,
  display_name character varying not null,
  public_name character varying not null,
  location json not null,
  timezone json not null,
  joined_at timestamp without time zone null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  status json not null,
  reg_at integer null,
  constraint clients_pkey primary key (id),
  constraint clients_id_key unique (id),
  constraint clients_username_key unique (username)
) TABLESPACE pg_default;

-- Note:
-- - We upsert with on_conflict="id" and explicitly set id = Freelancer user_id.
-- - Use SERVICE ROLE key for ingestion if RLS is enabled.

